before_script: cd coastbusters

language: java
dist: trusty
jdk:
- oraclejdk8
script:
  - ant build
  - sonar-scanner

addons:
  sonarcloud:
    organization: coastbusters
    token:
      secure: SONAR_TOKEN
